// Roteiro de entrevista do auditor por elemento WISE.
// Fonte: Treinamento de Auditor Júnior WISE² (ago/2026), slides 132–148 — "O que perguntar?".
export const INTERVIEW_GUIDE: Record<number, string[]> = {
  1: [
    "O que é segurança para você?",
    "Quais são os hábitos seguros que você possui?",
    "Você pratica segurança quando ninguém está olhando?",
    "Pra quem você faz segurança?",
    "Quais são os motivadores para que você atue com segurança?",
    "Foram estabelecidos objetivos anuais de saúde e segurança? Quem lidera o comitê?",
    "Qual a sua principal preocupação sobre saúde e segurança?",
    "Quem é o responsável pelas investigações de acidentes?",
    "Como você vê o compromisso da liderança em relação a segurança?",
    "Como teu lider lhe comunicou as expectativas de segurança?",
    "Quais objetivos internos você tem com seu chefe?",
    "Qual a porcentagem do seu bônus ligada a saúde e segurança?",
    "Tem um plano de trabalho com ações de saúde e segurança?",
    "Quem elabora o plano de segurança?",
    "Existe um budget de segurança?",
    "Quem faz a gestão e quem libera dinheiro para investir no tema?",
    "Você possui reuniões periódicas com o profissional de segurança?",
    "Quais as principais responsabilidades que você passou para a segurança?",
    "O que você faz pessoalmente para melhorar a segurança do seu site?",
    "Qual sua participação no sistema de segurança do sites, como auditorias, padrões, acidentes, reuniões, etc?",
    "Qual o maior risco neste site?",
    "O que é feito para solucionar ou reduzir este risco?",
    "Existe algum tema de saúde ou segurança que não é respeitado no site? Qual?",
    "O que estão fazendo sobre isso?",
    "Dê exemplos de como você demonstra compromisso com saúde e segurança das pessoas?",
    "Como você pode fazer para garantir que segurança é importante quando as pessoas não estão motivadas?",
    "Quanto tempo você dedica para saúde e segurança?",
    "Quantas vezes e quando costuma falar de saúde e segurança com sua equipe?",
    "Quando olham o plano de segurança do site?",
    "Qual foi a alguma vez que você conversou com algum operador sobre segurança? Como foi?",
    "Você vê e sente que seus gerentes e lideres tem realmente segurança como parte do negócio?",
    "Existe algum processo estruturado de reconhecimento de trabalho seguro ou descumprimento de norma?",
    "Você se lembra do último reconhecimento e de alguma sanção por descumprimento de regras. Nas avaliações de desempenho da sua equipe, também são considerados desempenho em segurança? Se sim, quais?",
    "Exemplos: Metas individuais e da equipe dele. Você acredita que a política de segurança e um pilar que guia os sistemas e os procedimentos?",
    "Você tem algum exemplo que utilizou a política de saúde e segurança para alavancar os padrões e índices de segurança?",
  ],
  2: [
    "Existe uma política de saúde e segurança?",
    "Está assinada pela liderança? (do site ou corporativo) Foi comunicada?(verificar em entrevistas, sala e campo) - entrevista - Há participação das pessoas do site na revisão da Política?(verificar em entrevistas, sala e campo) De que forma se compartilha e divulga a Política?",
    "Como se aplica a política para o negócio (exemplos)? Em que momento? (verificar em entrevistas, sala e campo) Para que serve a política de saúde e segurança?",
    "Como você participou na construção da Política?",
    "O que você entende da política?",
    "Em que momento as pessoas tem o primeiro contato com a política?",
    "Há uma forma de garantir o entendimento (compreensão) da política?",
    "Em que local posso encontrar a política?",
  ],
  3: [
    "Possui procedimentos de segurança?",
    "Cite alguns... Onde posso encontra-los?",
    "Você possui política de ação disciplinar? Como funciona? Já precisou aplicar?",
    "Me conte o que ocorreu. Possui ferramentas para identificar situações anormais nos locais de trabalho? Como funciona?",
    "Possui regras gerais de cumprimento de segurança? Regras de Ouro.. Quais são?",
    "Possui as tarefas que precisam de permissões especiais devidamente mapeadas na sua área de trabalho?",
    "Todos os EPIs estão sempre a disposição para realização das atividades da sua área?",
    "Existe um plano de emergência para o site? Possui gestão de químicos?",
    "Como identificar um produto e saber como proceder em emergências?",
    "Como é a gestão de riscos da sua área?",
    "Há um levantamento de perigos e riscos da área?",
    "Quais procedimentos possui na sua área? Quem os elaborou?",
    "Qual periodicidade de treinamentos?",
    "Se eu perguntar sobre estes procedimentos para seu time, eles vão saber falar sobre eles?",
    "Como você garante que os operadores estão cumprindo as normas?",
    "Possui processo de LOTO na sua área? Como funciona? Há procedimento?",
    "Possui etiquetas de segurança (manutenção autônoma) na área?",
    "Quem é responsável pela gestão?",
    "Existem prazos diferenciados para solução das etiquetas?",
    "Como garante que pessoas de outras áreas sigam as regras na sua área?",
    "Terceiros, realizam trabalho na sua área?",
    "Como é a gestão de segurança para eles?",
    "Como funciona o processo de gestão de mudanças?",
    "Como faz a gestão de disciplina na sua área?",
    "Conhece os padrões corporativos da Danone? Quais são?",
    "Quais são aplicáveis na sua área?",
    "Participa de algum fórum que fala de padrões?",
    "Compartilha boas práticas entre plantas?",
    "Pode citar alguma recente ou que se lembre?",
  ],
  4: [
    "Com que frequência se comunicam os KPIs objetivos de segurança?",
    "Foi informado aos empregados suas responsabilidades de saúde e segurança? (Entrevista no campo)",
    "Existem painéis ou quadros de comunicação de planos e metas, devidamente atualizados?",
    "Possuem sistema com gestão que assegura a devolutiva das ações, planos, desvios, etc? (Entrevista no campo)",
    "Todos no site possuem objetivos de saúde e segurança?",
    "Quais são seus objetivos pessoais?",
    "Possui algum objetivo coletivo ou social de saúde e segurança?",
    "Qual seu plano para alcançar os objetivos?",
    "Com qual critério se decide se alcançam ou não (há monitoramento da liderança constante)?",
    "Se o objetivo não é alcançado o que ocorre?",
    "Existe algum reconhecimento se o objetivo é alcançado?",
    "Individual / coletivo? (Verifique no campo)",
    "Existem reuniões ou fóruns para se falar de objetivos? Quando, qual frequência?",
    "Qual o principal objetivo do site?",
    "Qual seu principal objetivo?",
    "O que faz para apoiar a todo site a buscar os objetivos?",
    "Possui um plano de segurança especifico para sua área?",
    "Possui recursos disponíveis para trabalhar com prevenção (budget, investimentos, etc)?",
  ],
  5: [
    "Quais são os planos estratégicos para gerenciar segurança no site?",
    "Há estudos de saúde e ergonomia? Quais?",
    "Há profissional de área de saúde? Há campanhas de saúde?",
    "Quem é responsável das estatísticas de acidentes?",
    "O que você entende que é sua responsabilidade na organização?",
    "Que capacitação / treinamentos tem recebido?",
    "Que função você tem no comitê de segurança, o que faz efetivamente?",
    "Como e quando realiza uma auditoria de comportamento? (Solicitar documentos como exemplos)",
    "Há um plano de desenvolvimento / capacitação para os profissionais de segurança?",
    "Que auditorias você realiza como profissional de segurança?",
    "Conhece os padrões (Standards) corporativos?",
    "Quem coordena e trabalha com eles no site?",
    "De que maneira a organização, trabalha o sistema de segurança? Qual papel da liderança?",
    "Qual foi ou tem sido sua influência com a liderança?",
    "Quais as atividades faz o profissional de segurança no dia a dia?",
    "Considera o site um local de trabalho seguro?",
    "Quais os 3 principais riscos do site? Mais algum risco?",
  ],
  6: [
    "Possui formação de Wise (Treinamento de Wise para liderança)?",
    "Quais os principais riscos do site?",
    "Quais os riscos da sua área?",
    "Regularmente você averigua as preocupações de saúde e segurança de seus funcionários? (Entrevista no campo)",
    "Quanto tempo dedica para a segurança? (Entrevista no campo)",
    "Como se tratam as questões de segurança em sua área?",
    "Cite exemplos? (Entrevista o campo também)",
    "Há ferramentas para reportar desvios, riscos de acidentes? Como funcionam?",
    "Em caso de descumprimento de alguma regra, o que se faz?",
    "Você usa alguma ferramenta de segurança? Qual? Qual frequência?",
    "Conte-me sobre a última vez. Você já participou de uma auditoria Wise? Qual foi seu papel?",
    "Quem é responsável por segurança do seu site?",
    "Me conte sobre alguma mudança da sua área (processo, máquinas, equipamentos)?",
    "Você observou riscos e aspectos de saúde e segurança? Quais?",
    "Qual seu papel em saúde e segurança nesta planta?",
    "Como você motiva seu time em trabalhar com saúde e segurança?",
    "Possui política de consequencias de saúde e segurança no site? Já utilizou?",
    "Quais são os objetivos e metas em segurança da sua área, os seus e dos funcionário? Como você acompanha?",
  ],
  7: [
    "Quais são os fóruns que usam para falar do tema de saúde e segurança? Como funciona?",
    "Possui algum comitê que trata de saúde e segurança?",
    "Qual a frequência das reuniões?",
    "Quem lidera o comitê de segurança?",
    "Existe uma pauta padrão discutida no comitê, qual a dinâmica. Possui algum outro fórum de reunião sobre saúde e segurança?",
    "O site possui um coordenador de emergências?",
    "Existe um plano de emergência, como funciona? Possui algum subcomitê?",
    "Pessoas da operação participam de alguma forma do comitê ou subcomitê?",
    "Como os subcomitês e comitês se integram?",
    "Tendo realizado treinamento de Wise para liderança, me explique o que você entende do elemento de organização integrada?",
    "Acredita que o elemento funciona bem em seu site, quais são suas maiores dificuldades?",
    "Quais atividades desenvolve para reduzir os riscos em sua área de trabalho?",
    "O site possui programa de \"Dono\" de área?",
    "Todas as áreas possuem um dono? Como funciona?",
    "De que forma utiliza as ferramentas de gestão de segurança em sua rotina com a equipe? (GOS, APR, Investigação de acidentes, etc)?",
    "Existe algum programa de destaque das pessoas diferenciadas em segurança, fazendo com que ela se torne um braço da segurança (tema especifico, treinamentos, padrinho, etc)?",
  ],
  8: [
    "São reconhecidos os que cumprem as regras de segurança?",
    "São reconhecidos os comportamentos de segurança?",
    "De que forma promovem a prevenção no site?",
    "Como chegam as proposta de segurança aos líderes?",
    "Há alguma ferramenta formal?",
    "Como são dados os feedback as solicitações e inputs da operação?",
    "Foi realizada alguma pesquisa de segurança neste último ano?",
    "Quem que reconhece pelo alcance dos objetivos ligados a saúde e segurança ? De que forma?",
    "Lembra-se do último evento de celebração sobre saúde e segurança?",
    "Quem você reconhece como modelo em segurança? Porque?",
    "Você recebeu algum reconhecimento de saúde e segurança? Qual? Porque?",
    "Existe um sistema de disciplina implementado? Como funciona?",
    "Me dê um exemplo de algum caso?",
    "Qual sua motivação para trabalhar com segurança no dia a dia?",
    "Saúde e segurança é importante no desempenho das suas atividades?",
    "Como estão seus objetivos e metas?",
    "Considera justa a forma de reconhecimentos em saúde e segurança no site?",
    "Conhece as regras de disciplina do site?",
    "Se não cumpri-las qual o impacto?",
    "Boas práticas ou ações de segurança implantadas em outro site são compartilhadas? Como?",
  ],
  9: [
    "A equipe foi informada sobre a necessidade de uso EPI?",
    "Possui placas e sinalizações de saúde e segurança?",
    "O sistema de gestão e identificação de produtos químicos ou substâncias perigosas é mantido atualizado?",
    "Como as informações do comitê de segurança chegam às pessoas?",
    "Diante a um comentário de segurança, as pessoas são positivas?",
    "Com que frequência você conversa com sua equipe de segurança?",
    "Conversas de segurança. Como sabemos que as pessoas aceitam as regras?",
    "Você pode me dizer algo sobre o último acidente? Quando foi, o que foi? Quais ações de melhoria?",
    "Foi dito que você possuem KPIs, objetivos de saúde e segurança?",
    "Você se lembra da última campanha de segurança e saúde que ocorreu?",
    "Há alguma identificação dos brigadistas e cipeiros?",
    "A liderança leva em consideração suas sugestões de segurança?",
    "Como e quando você pode dar sugestões?",
    "Você conhece boas práticas aplicadas em outro site?",
    "Qual é o incidente relatado com mais frequência?",
    "Como os riscos são comunicados? De que forma?",
    "Você conhece os planos de ação da última reunião do comitê de segurança?",
    "O que te motiva a detectar um risco?",
    "Para quem e como pode comunica-lo?",
  ],
  10: [
    "Você possui uma matriz para gerenciar os treinamentos? Como funciona?",
    "De que forma sua a matriz é alimentada e revisada?",
    "Atualmente qual é o recurso disponível para realizar os treinamentos conforme o planejado?",
    "Algum sistema é usado para orientar novos funcionários?",
    "Quais assuntos são observados durante a integração?",
    "Como você garante que os tópicos passados durante a integração sejam atendidos? Como verifica isso?",
    "Existe algum plano de treinamento para funcionários em período de experiência? Como funciona?",
    "No processo de seleção de algum novo funcionário, há alguma analise ou pergunta de segurança?",
    "Existem programas de informação e treinamento para a equipe, a fim de aumentar a conscientização sobre aspectos potencialmente perigosos para sua saúde?",
    "Como você se certifica de que as pessoas entenderam os temas dos treinamentos?",
    "Você recebeu treinamento em segurança? Qual foi o último? Quando?",
    "Você possui treinamento de Wise? Quando recebeu?",
    "Quais observações são feitas no campo para controlar as habilidades adquiridas durante o treinamento?",
    "Quando há mudança de função ou área, há algum treinamento?",
    "Dentro dos perfis e descrições de funções, há itens de saúde e segurança como escopo e/ou responsabilidade?",
    "Que treinamento você recebeu como líder?",
    "Possui uma lista de multiplicadores dos treinamentos de saúde e segurança(instrutores internos e externos)?",
    "Como garante que estão aptos para dar os treinamentos?",
    "Quais são os treinamentos de segurança ministrados pela liderança? Quais líderes estão aptos?",
    "Qual é avaliação de reação pós treinamento?",
    "Como é verificada a eficácia destes treinamentos?",
    "Como gerencia os treinamentos obrigatórios? Quais são eles?",
    "Atualmente como está o atingimento dos treinamentos mandatórios?",
    "Se não realizado, qual é o procedimento? Existe meta de treinamento?",
    "Horas, números de pessoas etc?",
  ],
  11: [
    "Há um procedimento de investigação de acidentes e incidentes?",
    "Supervisores / lideres participam das investigações?",
    "O reporte é compartilhado com outros sites pra aprendizados?",
    "Os gerentes participam da investigação?",
    "Ocorreu algum acidente na sua área?",
    "Explique o que foi, quando e quais as principais ações de prevenção?",
    "Se ocorrer um acidente com você agora, qual o procedimento?",
    "Qual foi o último acidente do site? Quem divulga os acidentes?",
    "Tem ideia de quantos acidentes/ incidentes HIPO ocorreram este ano?",
    "Que sistema utilizam para chegar a causa do acidente?",
    "Você recebeu treinamento para investigar acidente? De quanto tempo e quando?",
    "Você já participou de alguma investigação de acidentes, qual foi seu papel?",
    "Onde são tratadas as ações dos acidentes/ incidentes?",
    "Quais das ações realizadas foram feitos análise da eficácia?",
  ],
  12: [
    "Nas auditorias participam o Gerente/Diretor do site?",
    "Há um plano de auditoria estruturado? Como funciona?",
    "Que tipo de Auditorias realizam em sua área?",
    "Possui auditorias comportamentais e estruturais? Quem as aplica? Conte-me como funciona?",
    "Como se administram os achados da auditoria?",
    "Quem participa do desenvolvimento dos protocolos das auditorias?",
    "Os contratados são auditados? Qual frequência?",
    "Há alguma auditoria na administração?",
    "Possui auditoria de comportamento? Quem faz? São treinados?",
    "Se dá feedback especifico e se tomam ações corretivas?",
    "Que tipo de participação em auditorias tem a operação?",
    "Dos achados encontrados durante as auditorias, são realizadas estatísticas e planos de ação?",
    "Quais auditorias o seu time realiza?",
    "Que protocolos específicos são utilizados para controlar os trabalhos e atividades críticas?",
    "São realizadas auditorias internas no sistema de saúde e segurança?",
    "Quem realiza e qual periodicidade?",
  ],
  13: [
    "Quantas e quais são as empresas contratadas permanentes no site?",
    "Como se dá o processo de contratação, desde quando você defini que precisa de algum serviço terceiro?",
    "Quem é responsável pela gestão da contratada?",
    "Como são passadas as regras de segurança para os terceiros? Quando são passadas? Qual a periodicidade?",
    "Os gestores de cada área, sabem quais são os terceiros que acessam ou realizam trabalhos na sua área?",
    "No processo de seleção de contratadas, é verificado desempenho de segurança das concorrentes ao contrato?",
    "Há uma gestão de KPIs para cada contratada?",
    "Acidentes com contratados são reportados e investigados da mesma forma que os acidentes com Danoners?",
    "Há um processo de auditoria realizadas nas contratadas? Qual a periodicidade?",
    "Caso possua auditorias, o que é feito com os resultados?",
    "A visão de zero acidentes é entendida e aceita pelas contratadas?",
    "Há um controle de documentação, treinamentos, certificações, etc. necessárias para realização do trabalho de acordo com leis e normas?",
    "São realizadas reuniões trimestrais para avaliação dos programas de segurança e feedbacks?",
    "Há uma política e consequencias implementada pelo contratado?",
    "Os contratados participam de todos os programas de saúde e segurança?",
    "Os gestores do contrato se envolvem na gestão de segurança dos contratados? Qual periodicidade? (mensal, quinzenal, semanal?)",
  ],
};
