import {
  Building2,
  ClipboardCheck,
  Construction,
  FlameKindling,
  FlaskConical,
  Footprints,
  Forklift,
  Gauge,
  GraduationCap,
  Handshake,
  HardHat,
  MessagesSquare,
  Network,
  PackageOpen,
  ScrollText,
  Search,
  ShieldCheck,
  Sparkles,
  Target,
  Truck,
  UserRound,
  Users,
  Warehouse,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  Building2,
  ClipboardCheck,
  Construction,
  FlameKindling,
  FlaskConical,
  Footprints,
  Forklift,
  Gauge,
  GraduationCap,
  Handshake,
  HardHat,
  MessagesSquare,
  Network,
  PackageOpen,
  ScrollText,
  Search,
  ShieldCheck,
  Sparkles,
  Target,
  Truck,
  UserRound,
  Users,
  Warehouse,
  Wrench,
};

export function ElementIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? ShieldCheck;
  return <Icon className={className} />;
}
